name: Trigger Markdown Page Workflow

on:
  release:
    types: [published, created, released]

jobs:
  trigger-remote-workflow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger markdown-page workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
        repository: thewrightmatt/markdown-page
        event-type: calculator-release
        client-payload: |
          {
            "release_tag": "${{ github.event.release.tag_name }}",
            "release_name": "${{ github.event.release.name }}",
            "release_url": "${{ github.event.release.html_url }}",
            "repository": "${{ github.repository }}"
          }
